# Generated by Django 5.0 on 2025-12-03 16:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('area', models.DecimalField(decimal_places=2, help_text='Area in acres', max_digits=10)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('planted', 'Planted'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('sold', 'Sold')], default='planned', max_length=20)),
                ('expected_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Expected yield in kg', max_digits=10, null=True)),
                ('actual_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Actual yield in kg', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='crops/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-planting_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10)),
                ('category', models.CharField(choices=[('crop_sale', 'Crop Sale'), ('livestock_sale', 'Livestock Sale'), ('seed_purchase', 'Seed Purchase'), ('fertilizer_purchase', 'Fertilizer Purchase'), ('pesticide_purchase', 'Pesticide Purchase'), ('equipment_purchase', 'Equipment Purchase'), ('fuel', 'Fuel'), ('labor', 'Labor Cost'), ('veterinary', 'Veterinary Services'), ('maintenance', 'Maintenance'), ('utilities', 'Utilities'), ('other', 'Other')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=300)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('seed', 'Seeds'), ('fertilizer', 'Fertilizers'), ('pesticide', 'Pesticides'), ('equipment', 'Equipment'), ('feed', 'Animal Feed'), ('medicine', 'Veterinary Medicine'), ('fuel', 'Fuel'), ('other', 'Other')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('kg', 'Kilograms'), ('lbs', 'Pounds'), ('ltr', 'Liters'), ('gal', 'Gallons'), ('bag', 'Bags'), ('pcs', 'Pieces'), ('unit', 'Units')], max_length=10)),
                ('reorder_level', models.DecimalField(decimal_places=2, help_text='Minimum quantity before reorder', max_digits=10)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Storage location', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cattle', 'Cattle'), ('poultry', 'Poultry'), ('sheep', 'Sheep'), ('goat', 'Goat'), ('pig', 'Pig'), ('other', 'Other')], max_length=20)),
                ('breed', models.CharField(max_length=100)),
                ('tag_number', models.CharField(max_length=50, unique=True)),
                ('date_acquired', models.DateField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('status', models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('under_treatment', 'Under Treatment'), ('pregnant', 'Pregnant'), ('sold', 'Sold'), ('deceased', 'Deceased')], default='healthy', max_length=20)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=8, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='livestock/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Livestock',
                'ordering': ['-date_acquired'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('planting', 'Planting'), ('irrigation', 'Irrigation'), ('fertilization', 'Fertilization'), ('pesticide_application', 'Pesticide Application'), ('weeding', 'Weeding'), ('harvesting', 'Harvesting'), ('feeding', 'Animal Feeding'), ('vaccination', 'Vaccination'), ('health_check', 'Health Check'), ('milking', 'Milking'), ('maintenance', 'Equipment Maintenance'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('materials_used', models.TextField(blank=True, help_text='Materials and quantities used')),
                ('notes', models.TextField(blank=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='activities/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('related_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='farm.crop')),
                ('related_livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='farm.livestock')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('due_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('related_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='farm.crop')),
                ('related_livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='farm.livestock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('manager', 'Farm Manager'), ('worker', 'Worker'), ('consultant', 'Consultant')], default='farmer', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('farm_name', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('farm_size', models.DecimalField(blank=True, decimal_places=2, help_text='Farm size in acres', max_digits=10, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('temperature_high', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_low', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('rainfall', models.DecimalField(blank=True, decimal_places=2, help_text='Rainfall in mm', max_digits=6, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('conditions', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Weather Data',
                'ordering': ['-date'],
            },
        ),
    ]
